#!/usr/bin/env bash
# FilePath: scripts/release/update-cask.sh
# Renders packaging/homebrew/Casks/simple-voice.rb for one release and, in publish mode, pushes
# it to the tap repository so `brew upgrade` picks the release up.
#
# Rendering pins `version` and the DMG's real `sha256`, replaces the template's own header with
# a pointer back here, and - for a Developer ID signed and notarized build - removes the block
# between the `unsigned-build` markers (the quarantine-clearing postflight and its caveat),
# which only ad-hoc signed builds need.
#
# Usage:
#   scripts/release/update-cask.sh render  VERSION SHA256 SIGNED    print the rendered cask
#   scripts/release/update-cask.sh publish VERSION SHA256 SIGNED    commit it to the tap
#
# SIGNED is `true` or `false`. Publish needs HOMEBREW_TAP_TOKEN (a token with contents:write on
# the tap repository); HOMEBREW_TAP_REPO overrides the default yuyudhan/homebrew-tap.
set -euo pipefail

root="$(cd "$(dirname "$0")/../.." && pwd)"
template="${root}/packaging/homebrew/Casks/simple-voice.rb"

usage() {
    echo "usage: $0 render|publish VERSION SHA256 true|false" >&2
    exit 1
}

[ "$#" -eq 4 ] || usage
mode="$1"
version="$2"
sha256="$3"
signed="$4"

case "$mode" in render | publish) ;; *) usage ;; esac
[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || {
    echo "update-cask: VERSION must be MAJOR.MINOR.PATCH (got '${version}')" >&2
    exit 1
}
[[ "$sha256" =~ ^[0-9a-f]{64}$ ]] || {
    echo "update-cask: SHA256 must be 64 lowercase hex characters" >&2
    exit 1
}
case "$signed" in true | false) ;; *) usage ;; esac

render() {
    awk -v version="$version" -v sha="$sha256" -v signed="$signed" '
        NR == 1 {
            print "# Generated by scripts/release/update-cask.sh in yuyudhan/simple-voice from"
            print "# packaging/homebrew/Casks/simple-voice.rb; edit the template there, not this file."
            header = 1
            next
        }
        header && /^#/ { next }
        { header = 0 }
        /^[[:space:]]*version "/ { sub(/"[^"]*"/, "\"" version "\"") }
        /^[[:space:]]*sha256 / { sub(/sha256 .*/, "sha256 \"" sha "\"") }
        /# unsigned-build:begin/ { skipping = (signed == "true"); next }
        /# unsigned-build:end/ { skipping = 0; next }
        skipping { next }
        /^[[:space:]]*$/ { if (blank) next; blank = 1; print; next }
        { blank = 0 }
        { print }
    ' "$template"
}

if [ "$mode" = "render" ]; then
    render
    exit 0
fi

: "${HOMEBREW_TAP_TOKEN:?HOMEBREW_TAP_TOKEN must be set to publish the cask}"
tap_repo="${HOMEBREW_TAP_REPO:-yuyudhan/homebrew-tap}"

workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' EXIT

git clone --depth 1 \
    "https://x-access-token:${HOMEBREW_TAP_TOKEN}@github.com/${tap_repo}.git" "${workdir}/tap"
mkdir -p "${workdir}/tap/Casks"
render >"${workdir}/tap/Casks/simple-voice.rb"

cd "${workdir}/tap"
if git diff --quiet -- Casks/simple-voice.rb && git ls-files --error-unmatch Casks/simple-voice.rb \
    >/dev/null 2>&1; then
    echo "update-cask: ${tap_repo} already carries simple-voice ${version}"
    exit 0
fi

git config user.name "${GIT_AUTHOR_NAME:-simple-voice release}"
git config user.email "${GIT_AUTHOR_EMAIL:-simple-voice-release@users.noreply.github.com}"
git add Casks/simple-voice.rb
git commit -m "🔖 Update simple-voice to ${version}"
git push origin HEAD
echo "update-cask: published simple-voice ${version} to ${tap_repo}"
