// FilePath: src/features/settings/general/languages.ts
// Languages Whisper recognises well, keyed by the ISO 639-1 code stored in settings.

export const LANGUAGE_NAMES: Record<string, string> = {
    en: "English",
    hi: "Hindi",
    af: "Afrikaans",
    ar: "Arabic",
    bg: "Bulgarian",
    bn: "Bengali",
    ca: "Catalan",
    cs: "Czech",
    da: "Danish",
    de: "German",
    el: "Greek",
    es: "Spanish",
    fa: "Persian",
    fi: "Finnish",
    fr: "French",
    gu: "Gujarati",
    he: "Hebrew",
    hr: "Croatian",
    hu: "Hungarian",
    id: "Indonesian",
    it: "Italian",
    ja: "Japanese",
    kn: "Kannada",
    ko: "Korean",
    ml: "Malayalam",
    mr: "Marathi",
    ms: "Malay",
    ne: "Nepali",
    nl: "Dutch",
    no: "Norwegian",
    pa: "Punjabi",
    pl: "Polish",
    pt: "Portuguese",
    ro: "Romanian",
    ru: "Russian",
    sk: "Slovak",
    sr: "Serbian",
    sv: "Swedish",
    sw: "Swahili",
    ta: "Tamil",
    te: "Telugu",
    th: "Thai",
    tl: "Tagalog",
    tr: "Turkish",
    uk: "Ukrainian",
    ur: "Urdu",
    vi: "Vietnamese",
    zh: "Chinese",
};

/** Always offered as one-click chips because the defaults are English plus Hindi/Hinglish. */
export const PRIMARY_LANGUAGES = ["en", "hi"];
